repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0

- repo: https://github.com/PyCQA/falke8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: [--max-line-length=80]

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.10.0
  hooks:
  - id: reorder-python-imports