"""user: add created_at column

Revision ID: 789ebe8ae9e7
Revises: 61d383bb7659
Create Date: 2025-02-11 00:22:26.027784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "789ebe8ae9e7"
down_revision: Union[str, None] = "61d383bb7659"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blog", "content", existing_type=sa.TEXT(), nullable=True)
    op.create_unique_constraint(None, "blog", ["slug"])
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            onupdate=sa.text("now()"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_constraint(None, "blog", type_="unique")
    op.alter_column("blog", "content", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
